// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnuojbgzsqhbbviztjkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxudW9qYmd6c3FoYmJ2aXp0amtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDk0MDUsImV4cCI6MjA1OTc4NTQwNX0.ieKVPk3cUR-_oHsWNO-YM3lU3LKWnpMWMhal4BoxVMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);